filetype plugin indent on
syntax on
set backspace=indent,eol,start
set number relativenumber
set shiftwidth=4 tabstop=4 softtabstop=4

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

set path=.,**

" yank to system clipboard
set clipboard=unnamedplus
